{{- /*
Generate secrets for duptwo
*/ -}}
{{- if and (not .Values.secret.existingSecret) .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duptwo.fullname" . }}-secret
  labels:
    {{- include "duptwo.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.secret.sessionSecret }}
  JWT_SECRET: {{ .Values.secret.jwtSecret }}
{{- end }}
